//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 06:48:40 PM CEST 
//


package com.logitags.cibet.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="authenticationProvider" type="{http://www.logitags.com}ClassDefBinding" minOccurs="0"/&gt;
 *         &lt;element name="notificationProvider" type="{http://www.logitags.com}ClassDefBinding" minOccurs="0"/&gt;
 *         &lt;element name="securityProvider" type="{http://www.logitags.com}ClassDefBinding" minOccurs="0"/&gt;
 *         &lt;element name="control" type="{http://www.logitags.com}ControlDefBinding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="actuator" type="{http://www.logitags.com}ActuatorBinding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="setpoint" type="{http://www.logitags.com}SetpointBinding" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "authenticationProvider",
    "notificationProvider",
    "securityProvider",
    "control",
    "actuator",
    "setpoint"
})
@XmlRootElement(name = "cibet")
public class Cibet {

    protected ClassDefBinding authenticationProvider;
    protected ClassDefBinding notificationProvider;
    protected ClassDefBinding securityProvider;
    protected List<ControlDefBinding> control;
    protected List<ActuatorBinding> actuator;
    protected List<SetpointBinding> setpoint;

    /**
     * Gets the value of the authenticationProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ClassDefBinding }
     *     
     */
    public ClassDefBinding getAuthenticationProvider() {
        return authenticationProvider;
    }

    /**
     * Sets the value of the authenticationProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassDefBinding }
     *     
     */
    public void setAuthenticationProvider(ClassDefBinding value) {
        this.authenticationProvider = value;
    }

    /**
     * Gets the value of the notificationProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ClassDefBinding }
     *     
     */
    public ClassDefBinding getNotificationProvider() {
        return notificationProvider;
    }

    /**
     * Sets the value of the notificationProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassDefBinding }
     *     
     */
    public void setNotificationProvider(ClassDefBinding value) {
        this.notificationProvider = value;
    }

    /**
     * Gets the value of the securityProvider property.
     * 
     * @return
     *     possible object is
     *     {@link ClassDefBinding }
     *     
     */
    public ClassDefBinding getSecurityProvider() {
        return securityProvider;
    }

    /**
     * Sets the value of the securityProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassDefBinding }
     *     
     */
    public void setSecurityProvider(ClassDefBinding value) {
        this.securityProvider = value;
    }

    /**
     * Gets the value of the control property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the control property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getControl().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ControlDefBinding }
     * 
     * 
     */
    public List<ControlDefBinding> getControl() {
        if (control == null) {
            control = new ArrayList<ControlDefBinding>();
        }
        return this.control;
    }

    /**
     * Gets the value of the actuator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the actuator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getActuator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ActuatorBinding }
     * 
     * 
     */
    public List<ActuatorBinding> getActuator() {
        if (actuator == null) {
            actuator = new ArrayList<ActuatorBinding>();
        }
        return this.actuator;
    }

    /**
     * Gets the value of the setpoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the setpoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSetpoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SetpointBinding }
     * 
     * 
     */
    public List<SetpointBinding> getSetpoint() {
        if (setpoint == null) {
            setpoint = new ArrayList<SetpointBinding>();
        }
        return this.setpoint;
    }

}
