//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.27 at 09:11:46 AM CEST 
//


package com.logitags.cibet.bindings;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ControlsBinding complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ControlsBinding"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;all&gt;
 *         &lt;element name="tenant" type="{http://www.logitags.com}InExBinding" minOccurs="0"/&gt;
 *         &lt;element name="event" type="{http://www.logitags.com}InExBinding" minOccurs="0"/&gt;
 *         &lt;element name="target" type="{http://www.logitags.com}InExBinding" minOccurs="0"/&gt;
 *         &lt;element name="method" type="{http://www.logitags.com}InExBinding" minOccurs="0"/&gt;
 *         &lt;element name="invoker" type="{http://www.logitags.com}InExBinding" minOccurs="0"/&gt;
 *         &lt;element name="stateChange" type="{http://www.logitags.com}InExBinding" minOccurs="0"/&gt;
 *         &lt;element name="condition" type="{http://www.logitags.com}InExBinding" minOccurs="0"/&gt;
 *         &lt;element name="customControls" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="customControl" type="{http://www.logitags.com}CustomControlBinding" maxOccurs="unbounded"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/all&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ControlsBinding", propOrder = {

})
public class ControlsBinding {

    protected InExBinding tenant;
    protected InExBinding event;
    protected InExBinding target;
    protected InExBinding method;
    protected InExBinding invoker;
    protected InExBinding stateChange;
    protected InExBinding condition;
    protected ControlsBinding.CustomControls customControls;

    /**
     * Gets the value of the tenant property.
     * 
     * @return
     *     possible object is
     *     {@link InExBinding }
     *     
     */
    public InExBinding getTenant() {
        return tenant;
    }

    /**
     * Sets the value of the tenant property.
     * 
     * @param value
     *     allowed object is
     *     {@link InExBinding }
     *     
     */
    public void setTenant(InExBinding value) {
        this.tenant = value;
    }

    /**
     * Gets the value of the event property.
     * 
     * @return
     *     possible object is
     *     {@link InExBinding }
     *     
     */
    public InExBinding getEvent() {
        return event;
    }

    /**
     * Sets the value of the event property.
     * 
     * @param value
     *     allowed object is
     *     {@link InExBinding }
     *     
     */
    public void setEvent(InExBinding value) {
        this.event = value;
    }

    /**
     * Gets the value of the target property.
     * 
     * @return
     *     possible object is
     *     {@link InExBinding }
     *     
     */
    public InExBinding getTarget() {
        return target;
    }

    /**
     * Sets the value of the target property.
     * 
     * @param value
     *     allowed object is
     *     {@link InExBinding }
     *     
     */
    public void setTarget(InExBinding value) {
        this.target = value;
    }

    /**
     * Gets the value of the method property.
     * 
     * @return
     *     possible object is
     *     {@link InExBinding }
     *     
     */
    public InExBinding getMethod() {
        return method;
    }

    /**
     * Sets the value of the method property.
     * 
     * @param value
     *     allowed object is
     *     {@link InExBinding }
     *     
     */
    public void setMethod(InExBinding value) {
        this.method = value;
    }

    /**
     * Gets the value of the invoker property.
     * 
     * @return
     *     possible object is
     *     {@link InExBinding }
     *     
     */
    public InExBinding getInvoker() {
        return invoker;
    }

    /**
     * Sets the value of the invoker property.
     * 
     * @param value
     *     allowed object is
     *     {@link InExBinding }
     *     
     */
    public void setInvoker(InExBinding value) {
        this.invoker = value;
    }

    /**
     * Gets the value of the stateChange property.
     * 
     * @return
     *     possible object is
     *     {@link InExBinding }
     *     
     */
    public InExBinding getStateChange() {
        return stateChange;
    }

    /**
     * Sets the value of the stateChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link InExBinding }
     *     
     */
    public void setStateChange(InExBinding value) {
        this.stateChange = value;
    }

    /**
     * Gets the value of the condition property.
     * 
     * @return
     *     possible object is
     *     {@link InExBinding }
     *     
     */
    public InExBinding getCondition() {
        return condition;
    }

    /**
     * Sets the value of the condition property.
     * 
     * @param value
     *     allowed object is
     *     {@link InExBinding }
     *     
     */
    public void setCondition(InExBinding value) {
        this.condition = value;
    }

    /**
     * Gets the value of the customControls property.
     * 
     * @return
     *     possible object is
     *     {@link ControlsBinding.CustomControls }
     *     
     */
    public ControlsBinding.CustomControls getCustomControls() {
        return customControls;
    }

    /**
     * Sets the value of the customControls property.
     * 
     * @param value
     *     allowed object is
     *     {@link ControlsBinding.CustomControls }
     *     
     */
    public void setCustomControls(ControlsBinding.CustomControls value) {
        this.customControls = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="customControl" type="{http://www.logitags.com}CustomControlBinding" maxOccurs="unbounded"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "customControl"
    })
    public static class CustomControls {

        @XmlElement(required = true)
        protected List<CustomControlBinding> customControl;

        /**
         * Gets the value of the customControl property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the customControl property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getCustomControl().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link CustomControlBinding }
         * 
         * 
         */
        public List<CustomControlBinding> getCustomControl() {
            if (customControl == null) {
                customControl = new ArrayList<CustomControlBinding>();
            }
            return this.customControl;
        }

    }

}
