//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.08.27 at 09:11:46 AM CEST 
//


package com.logitags.cibet.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.logitags.cibet.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InExBindingInclude_QNAME = new QName("http://www.logitags.com", "include");
    private final static QName _InExBindingExclude_QNAME = new QName("http://www.logitags.com", "exclude");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.logitags.cibet.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ControlsBinding }
     * 
     */
    public ControlsBinding createControlsBinding() {
        return new ControlsBinding();
    }

    /**
     * Create an instance of {@link Cibet }
     * 
     */
    public Cibet createCibet() {
        return new Cibet();
    }

    /**
     * Create an instance of {@link ClassDefBinding }
     * 
     */
    public ClassDefBinding createClassDefBinding() {
        return new ClassDefBinding();
    }

    /**
     * Create an instance of {@link ControlDefBinding }
     * 
     */
    public ControlDefBinding createControlDefBinding() {
        return new ControlDefBinding();
    }

    /**
     * Create an instance of {@link ActuatorBinding }
     * 
     */
    public ActuatorBinding createActuatorBinding() {
        return new ActuatorBinding();
    }

    /**
     * Create an instance of {@link SetpointBinding }
     * 
     */
    public SetpointBinding createSetpointBinding() {
        return new SetpointBinding();
    }

    /**
     * Create an instance of {@link PropertiesBinding }
     * 
     */
    public PropertiesBinding createPropertiesBinding() {
        return new PropertiesBinding();
    }

    /**
     * Create an instance of {@link SetpointActuatorBinding }
     * 
     */
    public SetpointActuatorBinding createSetpointActuatorBinding() {
        return new SetpointActuatorBinding();
    }

    /**
     * Create an instance of {@link InExBinding }
     * 
     */
    public InExBinding createInExBinding() {
        return new InExBinding();
    }

    /**
     * Create an instance of {@link CustomControlBinding }
     * 
     */
    public CustomControlBinding createCustomControlBinding() {
        return new CustomControlBinding();
    }

    /**
     * Create an instance of {@link ControlsBinding.CustomControls }
     * 
     */
    public ControlsBinding.CustomControls createControlsBindingCustomControls() {
        return new ControlsBinding.CustomControls();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "include", scope = InExBinding.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInExBindingInclude(String value) {
        return new JAXBElement<String>(_InExBindingInclude_QNAME, String.class, InExBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "exclude", scope = InExBinding.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createInExBindingExclude(String value) {
        return new JAXBElement<String>(_InExBindingExclude_QNAME, String.class, InExBinding.class, value);
    }

}
