//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.08 at 06:48:40 PM CEST 
//


package com.logitags.cibet.bindings;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.logitags.cibet.bindings package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ControlsBindingTenant_QNAME = new QName("http://www.logitags.com", "tenant");
    private final static QName _ControlsBindingEvent_QNAME = new QName("http://www.logitags.com", "event");
    private final static QName _ControlsBindingTarget_QNAME = new QName("http://www.logitags.com", "target");
    private final static QName _ControlsBindingMethod_QNAME = new QName("http://www.logitags.com", "method");
    private final static QName _ControlsBindingInvoker_QNAME = new QName("http://www.logitags.com", "invoker");
    private final static QName _ControlsBindingStateChange_QNAME = new QName("http://www.logitags.com", "stateChange");
    private final static QName _ControlsBindingCondition_QNAME = new QName("http://www.logitags.com", "condition");
    private final static QName _ControlsBindingCustomControl_QNAME = new QName("http://www.logitags.com", "customControl");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.logitags.cibet.bindings
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Cibet }
     * 
     */
    public Cibet createCibet() {
        return new Cibet();
    }

    /**
     * Create an instance of {@link ClassDefBinding }
     * 
     */
    public ClassDefBinding createClassDefBinding() {
        return new ClassDefBinding();
    }

    /**
     * Create an instance of {@link ControlDefBinding }
     * 
     */
    public ControlDefBinding createControlDefBinding() {
        return new ControlDefBinding();
    }

    /**
     * Create an instance of {@link ActuatorBinding }
     * 
     */
    public ActuatorBinding createActuatorBinding() {
        return new ActuatorBinding();
    }

    /**
     * Create an instance of {@link SetpointBinding }
     * 
     */
    public SetpointBinding createSetpointBinding() {
        return new SetpointBinding();
    }

    /**
     * Create an instance of {@link ControlsBinding }
     * 
     */
    public ControlsBinding createControlsBinding() {
        return new ControlsBinding();
    }

    /**
     * Create an instance of {@link PropertiesBinding }
     * 
     */
    public PropertiesBinding createPropertiesBinding() {
        return new PropertiesBinding();
    }

    /**
     * Create an instance of {@link SetpointActuatorBinding }
     * 
     */
    public SetpointActuatorBinding createSetpointActuatorBinding() {
        return new SetpointActuatorBinding();
    }

    /**
     * Create an instance of {@link InExAttributeBinding }
     * 
     */
    public InExAttributeBinding createInExAttributeBinding() {
        return new InExAttributeBinding();
    }

    /**
     * Create an instance of {@link CustomControlBinding }
     * 
     */
    public CustomControlBinding createCustomControlBinding() {
        return new CustomControlBinding();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "tenant", scope = ControlsBinding.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createControlsBindingTenant(String value) {
        return new JAXBElement<String>(_ControlsBindingTenant_QNAME, String.class, ControlsBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "event", scope = ControlsBinding.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createControlsBindingEvent(String value) {
        return new JAXBElement<String>(_ControlsBindingEvent_QNAME, String.class, ControlsBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "target", scope = ControlsBinding.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createControlsBindingTarget(String value) {
        return new JAXBElement<String>(_ControlsBindingTarget_QNAME, String.class, ControlsBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "method", scope = ControlsBinding.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createControlsBindingMethod(String value) {
        return new JAXBElement<String>(_ControlsBindingMethod_QNAME, String.class, ControlsBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InExAttributeBinding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "invoker", scope = ControlsBinding.class)
    public JAXBElement<InExAttributeBinding> createControlsBindingInvoker(InExAttributeBinding value) {
        return new JAXBElement<InExAttributeBinding>(_ControlsBindingInvoker_QNAME, InExAttributeBinding.class, ControlsBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InExAttributeBinding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "stateChange", scope = ControlsBinding.class)
    public JAXBElement<InExAttributeBinding> createControlsBindingStateChange(InExAttributeBinding value) {
        return new JAXBElement<InExAttributeBinding>(_ControlsBindingStateChange_QNAME, InExAttributeBinding.class, ControlsBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "condition", scope = ControlsBinding.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createControlsBindingCondition(String value) {
        return new JAXBElement<String>(_ControlsBindingCondition_QNAME, String.class, ControlsBinding.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CustomControlBinding }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.logitags.com", name = "customControl", scope = ControlsBinding.class)
    public JAXBElement<CustomControlBinding> createControlsBindingCustomControl(CustomControlBinding value) {
        return new JAXBElement<CustomControlBinding>(_ControlsBindingCustomControl_QNAME, CustomControlBinding.class, ControlsBinding.class, value);
    }

}
