-- Migration Script for Cibet 2.0. Must be executed AFTER software is completely updated on all nodes

update CIB_ARCHIVE a1 set a1.ARCHIVEID1 = (select cast(cast(a2.ARCHIVEID as CHAR(254)) as VARCHAR(255)) from CIB_ARCHIVE a2 where a2.ARCHIVEID = a1.ARCHIVEID) where a1.ARCHIVEID1 is null; 
alter table CIB_ARCHIVE alter column ARCHIVEID1 not null;
alter table CIB_ARCHIVE add primary key(ARCHIVEID1);
alter table CIB_ARCHIVE drop ARCHIVEID;
alter table CIB_ARCHIVE drop LASTARCHIVEID;

update CIB_DCCONTROLLABLE c1 set c1.DCCONTROLLABLEID1 = (select cast(cast(c2.DCCONTROLLABLEID as CHAR(254)) as VARCHAR(255)) from CIB_DCCONTROLLABLE c2 where c2.DCCONTROLLABLEID = c1.DCCONTROLLABLEID) where c1.DCCONTROLLABLEID1 is null;
alter table CIB_DCCONTROLLABLE alter column DCCONTROLLABLEID1 not null;
alter table CIB_DCCONTROLLABLE add primary key(DCCONTROLLABLEID1);
alter table CIB_DCCONTROLLABLE drop DCCONTROLLABLEID;

update CIB_RESOURCEPARAMETER r1 set r1.PARAMETERID1 = (select cast(cast(r2.PARAMETERID as CHAR(254)) as VARCHAR(255)) from CIB_RESOURCEPARAMETER r2 where r2.PARAMETERID = r1.PARAMETERID) where r1.PARAMETERID1 is null; 
update CIB_RESOURCEPARAMETER r1 set r1.ARCHIVEID1 = (select cast(cast(r2.ARCHIVEID as CHAR(254)) as VARCHAR(255)) from CIB_RESOURCEPARAMETER r2 where r2.PARAMETERID1 = r1.PARAMETERID1) where r1.ARCHIVEID1 is null; 
update CIB_RESOURCEPARAMETER r1 set r1.DCCONTROLLABLEID1 = (select cast(cast(r2.DCCONTROLLABLEID as CHAR(254)) as VARCHAR(255)) from CIB_RESOURCEPARAMETER r2 where r2.PARAMETERID1 = r1.PARAMETERID1) where r1.DCCONTROLLABLEID1 is null; 
alter table CIB_RESOURCEPARAMETER alter column PARAMETERID1 not null;
alter table CIB_RESOURCEPARAMETER add primary key(PARAMETERID1);
alter table CIB_RESOURCEPARAMETER add constraint ARCHIVE_FK foreign key (ARCHIVEID1) REFERENCES CIB_ARCHIVE (ARCHIVEID1);
alter table CIB_RESOURCEPARAMETER add constraint DCCONTROLLABLE_FK foreign key (DCCONTROLLABLEID1) REFERENCES CIB_DCCONTROLLABLE (DCCONTROLLABLEID1);
alter table CIB_RESOURCEPARAMETER drop PARAMETERID;
alter table CIB_RESOURCEPARAMETER drop ARCHIVEID;
alter table CIB_RESOURCEPARAMETER drop DCCONTROLLABLEID;

update CIB_LOCKEDOBJECT l1 set l1.LOCKEDOBJECTID1 = (select cast(cast(l2.LOCKEDOBJECTID as CHAR(254)) as VARCHAR(255)) from CIB_LOCKEDOBJECT l2 where l2.LOCKEDOBJECTID = l1.LOCKEDOBJECTID) where l1.LOCKEDOBJECTID1 is null; 
alter table CIB_LOCKEDOBJECT alter column LOCKEDOBJECTID1 not null;
alter table CIB_LOCKEDOBJECT add primary key(LOCKEDOBJECTID1);
alter table CIB_LOCKEDOBJECT drop LOCKEDOBJECTID;

update CIB_EVENTRESULT e1 set e1.EVENTRESULTID1 = (select cast(cast(e2.EVENTRESULTID as CHAR(254)) as VARCHAR(255)) from CIB_EVENTRESULT e2 where e2.EVENTRESULTID = e1.EVENTRESULTID) where e1.EVENTRESULTID1 is null; 
update CIB_EVENTRESULT e1 set e1.PARENTRESULT_ID1 = (select cast(cast(e2.PARENTRESULT_ID as CHAR(254)) as VARCHAR(255)) from CIB_EVENTRESULT e2 where e2.EVENTRESULTID1 = e1.EVENTRESULTID1) where e1.PARENTRESULT_ID1 is null; 
alter table CIB_EVENTRESULT alter column EVENTRESULTID1 not null;
alter table CIB_EVENTRESULT add primary key(EVENTRESULTID1);
alter table CIB_EVENTRESULT add constraint EVENTRESULT_FK foreign key (PARENTRESULT_ID1) REFERENCES CIB_EVENTRESULT (EVENTRESULTID1);
alter table CIB_EVENTRESULT drop EVENTRESULTID;
alter table CIB_EVENTRESULT drop PARENTRESULT_ID; 

