-- ----------------------------------------------
-- DROP STATEMENTS
-- ----------------------------------------------

--DROP TABLE CIB_RESOURCEPARAMETER;
--DROP TABLE CIB_ARCHIVE;
--DROP TABLE CIB_CONTROLLABLE;
--DROP TABLE CIB_LOCKEDOBJECT;
--DROP TABLE CIB_EVENTRESULT;
--DROP TABLE CIB_SEQUENCE;

CREATE TABLE CIB_ARCHIVE ( 
	ARCHIVEID VARCHAR(255) NOT NULL, 
	REMARK VARCHAR(255), 
	RESULT BLOB, 
	CHECKSUM VARCHAR(255), 
	CONTROLEVENT VARCHAR(50), 
	TARGETTYPE VARCHAR(255), 
	CREATEUSER VARCHAR(50), 
	CREATEDATE TIMESTAMP, 
	TENANT VARCHAR(255), 
	CASEID VARCHAR(60), 
	TARGET BLOB, 
	PRIMARYKEYID VARCHAR(50), 
	METHOD VARCHAR(255), 
	INVOKERCLASS VARCHAR(255), 
	INVOKERPARAM VARCHAR(255), 
	EXECUTIONSTATUS VARCHAR(50) NOT NULL, 
	VERSION NUMBER(19,0) NOT NULL, 
	RESOURCEHANDLERCLASS VARCHAR(255), 
	ENCRYPTED smallint DEFAULT 0 NOT NULL ,
	KEYREFERENCE VARCHAR(255),
	UNIQUEID VARCHAR(255),
	GROUPID VARCHAR(255),
	PRIMARY KEY (ARCHIVEID) 
);

-- ----------------------------------------------
-- DC
-- ----------------------------------------------

CREATE TABLE CIB_CONTROLLABLE ( 
	CONTROLLABLEID VARCHAR(255) NOT NULL, 
	CASEID VARCHAR(60), 
	CONTROLEVENT VARCHAR(50), 
	CREATEUSER VARCHAR(50) NOT NULL, 
	CREATEDATE TIMESTAMP NOT NULL, 
	CREATEADDRESS VARCHAR(255), 
	CREATEREMARK VARCHAR(255), 
	TARGETTYPE VARCHAR(255), 
	TARGET BLOB, 
	TENANT VARCHAR(255), 
	ACTUATOR VARCHAR(100) NOT NULL, 
	FIRSTAPPROVUSER VARCHAR(50), 
	FIRSTAPPROVALDATE TIMESTAMP, 
	FIRSTAPPROVADDR VARCHAR(255), 
	FIRSTAPPROVREMARK VARCHAR(255), 
	APPROVALUSER VARCHAR(50), 
	APPROVALDATE TIMESTAMP, 
	APPROVALADDRESS VARCHAR(255), 
	APPROVALREMARK VARCHAR(255),
	EXECUTIONSTATUS VARCHAR(50) NOT NULL, 
	VERSION NUMBER(19,0) NOT NULL, 
	PRIMARYKEYID VARCHAR(50), 
	METHOD VARCHAR(255), 
	INVOKERCLASS VARCHAR(255), 
	INVOKERPARAM VARCHAR(255), 
	RESOURCEHANDLERCLASS VARCHAR(255), 
	RESULT BLOB, 
	ENCRYPTED smallint DEFAULT 0 NOT NULL,
	KEYREFERENCE VARCHAR(255),
	UNIQUEID VARCHAR(255),
	SCHEDULEDDATE TIMESTAMP,
	EXECUTIONDATE TIMESTAMP,
	GROUPID VARCHAR(255),
	PRIMARY KEY (CONTROLLABLEID) 
);

CREATE TABLE CIB_RESOURCEPARAMETER ( 
	PARAMETERID VARCHAR(255) NOT NULL, 
	NAME VARCHAR2(255) NOT NULL, 
	PARAMETERTYPE VARCHAR2(50) NOT NULL, 
	CLASSNAME VARCHAR2(255) NOT NULL, 
	ENCODEDVALUE BLOB, 
	SEQUENCE NUMBER(19,0) NOT NULL, 
	DCCONTROLLABLEID VARCHAR(255), 
	ARCHIVEID VARCHAR(255), 
	STRINGVALUE VARCHAR2(255),
	FOREIGN KEY (ARCHIVEID) REFERENCES CIB_ARCHIVE (ARCHIVEID),
	FOREIGN KEY (DCCONTROLLABLEID) REFERENCES CIB_DCCONTROLLABLE (DCCONTROLLABLEID),
	PRIMARY KEY (PARAMETERID) 
);


-- ----------------------------------------------
-- LOCK
-- ----------------------------------------------

CREATE TABLE CIB_LOCKEDOBJECT (
	LOCKEDOBJECTID VARCHAR(255) NOT NULL,
	LOCKDATE TIMESTAMP NOT NULL,
	LOCKREMARK VARCHAR2(255),
	LOCKEDBY VARCHAR2(50) NOT NULL,
	LOCKSTATE VARCHAR2(50) NOT NULL,
	OBJECTID VARCHAR2(50),
	OBJECT	BLOB, 
	TARGETTYPE VARCHAR2(255), 
	LOCKEDEVENT VARCHAR2(50) NOT NULL, 
	METHOD VARCHAR2(255), 
	TENANT VARCHAR2(255), 
	UNLOCKDATE TIMESTAMP,
	UNLOCKREMARK VARCHAR2(255),
	UNLOCKEDBY VARCHAR2(50),
	VERSION NUMBER(19,0) NOT NULL,
	primary key(LOCKEDOBJECTID)
);

CREATE TABLE CIB_EVENTRESULT (
	EVENTRESULTID VARCHAR(255) NOT NULL,
   PARENTRESULT_ID VARCHAR(255),
   EVENT VARCHAR2(50) NOT NULL,
   RESOURC VARCHAR2(255),
   SENSOR VARCHAR2(50) NOT NULL,
   SETPOINTS VARCHAR2(255),
   ACTUATORS VARCHAR2(255),
   EXECUTIONSTATUS VARCHAR2(50) NOT NULL,
   TRACK_TENANT VARCHAR2(255),
   TRACK_USER VARCHAR2(50),
   EXECUTIONTIME TIMESTAMP NOT NULL,
   CASEID VARCHAR2(60),
   PRIMARY KEY (EVENTRESULTID),
   CONSTRAINT FKEVENTRESULT_PARENT FOREIGN KEY (PARENTRESULT_ID) REFERENCES CIB_EVENTRESULT
   (EVENTRESULTID)
);

CREATE TABLE CIB_SEQUENCE (
	SEQUENCE				VARCHAR2(100) NOT NULL,
	HI						NUMBER(19,0), 
	LASTUPDATE			TIMESTAMP,
	PRIMARY KEY(SEQUENCE)
);
      